import { createElement } from 'lwc';
import Lp2cParentComponentProgress from 'c/lp2cParentComponentProgress';

describe('c-lp2-c-parent-component-progress', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lp2-c-parent-component-progress', {
            is: Lp2cParentComponentProgress
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});