import { createElement } from 'lwc';
import Lp2cParentComponentSlider from 'c/lp2cParentComponentSlider';

describe('c-lp2-c-parent-component-slider', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lp2-c-parent-component-slider', {
            is: Lp2cParentComponentSlider
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});